---
title: shopify.gallery
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: submit@shopify.gallery
author: Hatch Inc.
description: An ever-growing collection of inspiring e-commerce stores built on Shopify.
baseurl: ''
url: http://shopify.gallery
date_format: "%d-%m-%y"
google_verification: 
google_analytics: UA-57545939-5
google_tag_manager: 
bing_verification: 
animated: false
show_related_posts: false
show_post_footers: false
show_social_icons: true
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false
disqus_shortname: 
facebook_comments: 
facebook_appid: 
facebook_comments_number: 10
github_username: 
bitbucket_username: 
stackoverflow_id: 
twitter_username: hatch_inc
skype_username: 
steam_nickname: 
google_plus_id: 
linkedin_username: 
angellist_username: 
medium_id: 
bitcoin_url: 
paypal_url: 
flattr_button: 
show_sharing_icons: false
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false
text:
  share_buttons:
    text: Share this post!
    facebook: Share on Facebook
    twitter: Share on Twitter
    googleplus: Share on Google+
    linkedin: Share on LinkedIn
    digg: Share on Digg
    tumblr: Share on Tumblr
    reddit: Share on Reddit
    stumbleupon: Share on StumbleUpon
    hackernews: Share on Hacker News
  post:
    updated: Updated
    minute_read: minute read
    related_posts: Related Posts
  index:
    coming_soon: Coming soon...
  contact:
    email: Your Email Address
    site: Store URL
    credit: Credit (Designer/Developer)
    subject: New submission!
    submit: Submit
    ajax:
      sending: sending..
      sent: Message sent!
      error: Error!
  thanks: Thanks for submitting a Shopify store. Your awesome!
  og_locale: en_US
markdown: kramdown
redcarpet:
  extensions:
  - smart
  - tables
  - with_toc_data
permalink: pretty
paginate: 6
paginate_path: page:num
sass:
  compressed: true
gems:
- jekyll-paginate
- jekyll-sitemap
exclude:
- vendor
